(load "util.lisp")
(load "staterep.lisp")

(defun stateEqual (s1 s2)
  (do ((i 1 (1+ i))
       (sequal t))
    ((or (> i (length s1))
         (null sequal)) sequal)
    (do ((j 1 (1+ j)))
       ((> j (length (nth i s1))))
       (if (not (eql (nth j (nth i s1)) (nth j (nth i s2))))
          (setq sequal nil)) )))

(setf s1 (loadGameState "SBP-level0.txt"))
(setf s2 (loadGameState "SBP-level0-solved.txt"))
(format t "~a~%" (stateEqual s1 s2))
